server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_01?serverTimezone=UTC
    username: root
    password: 12345
  application:
    name: cloud-consumer-student-80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    instance-id: cloud-consumer-student-80:80